version: '3.9'

services:
  web:
    build: .
    container_name: pteczestochowa
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: "npm run dev"

  db:
    image: postgres:15
    container_name: pteczestochowa-db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  pgdata:
