import type { Metadata } from "next";
import "@/styles/globals.css";
import ApollosProvider from "@/providers/apollo-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased !bg-[#f8f4f2] !text-[#424242] text-base`}>
          <ApollosProvider>
          {children}
          </ApollosProvider>
      </body>
    </html>
  );
}
